/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unibo.wenvusage;
import org.junit.Before;
import org.junit.After;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {

    @Before public void setup(){
        System.out.println("setup");
    }
    @After public void terminate(){
        System.out.println("stop");
    }
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
    @Test public void testAnotherko(){
        System.out.println("testko");
        //fail();
    }
    @Test public void testAnotherok(){
        System.out.println("testok");
        assertTrue(2==2);
    }
}
